window.defaultGameData = window.defaultGameData || {};
window.defaultGameData["only大人"] = {
  // Adult (Level 4-6) - 辛辣、成人話題、飲酒
  truth: [
    { id: "ad_t_01", text: "你曾經在公共場合做過那檔事嗎？", level: 5 },
    {
      id: "ad_t_02",
      text: "在場的人之中，如果必須選一個人發生關係，你會選誰？",
      level: 5,
    },
    {
      id: "ad_t_03",
      text: "你最短的一次戀情（或性行為）持續多久？",
      level: 4,
    },
    {
      id: "ad_t_04",
      text: "你曾經對伴侶說謊關於高潮的事嗎？",
      level: 5,
    },
    { id: "ad_t_05", text: "你有過一夜情嗎？感覺如何？", level: 5 },
    { id: "ad_t_06", text: "你最喜歡的體位是什麼？", level: 5 },
    { id: "ad_t_07", text: "你曾經偷看過伴侶的手機嗎？", level: 4 },
    { id: "ad_t_08", text: "你覺得性重要還是愛重要？", level: 4 },
    { id: "ad_t_09", text: "你曾經幻想過朋友的伴侶嗎？", level: 5 },
    {
      id: "ad_t_10",
      text: "你收過或發過最露骨的訊息是什麼？",
      level: 5,
    },
    { id: "ad_t_11", text: "你曾經在夢裡夢過在場的誰？", level: 4 },
    { id: "ad_t_12", text: "你最奇怪的性幻想是什麼？", level: 5 },
    { id: "ad_t_13", text: "你曾經同時和兩個人曖昧嗎？", level: 4 },
    {
      id: "ad_t_14",
      text: "你覺得自己性能力幾分（滿分10）？",
      level: 5,
    },
    {
      id: "ad_t_15",
      text: "你曾經在喝醉後做過最後悔的事是什麼？",
      level: 4,
    },
    { id: "ad_t_16", text: "你是否曾經對朋友有過非分之想？", level: 4 },
    { id: "ad_t_17", text: "你最喜歡異性身體的哪個部位？", level: 4 },
    { id: "ad_t_18", text: "你曾經被抓包過在看謎片嗎？", level: 4 },
    { id: "ad_t_19", text: "你曾經在游泳池裡尿尿嗎？", level: 3 },
    { id: "ad_t_20", text: "你是否曾經為了性而說謊？", level: 5 },
    { id: "ad_t_21", text: "你曾經在車震過嗎？", level: 5 },
    { id: "ad_t_22", text: "你最喜歡的內衣顏色？", level: 4 },
    {
      id: "ad_t_23",
      text: "你曾經和比自己大/小10歲以上的人交往嗎？",
      level: 4,
    },
    { id: "ad_t_24", text: "你曾經在辦公室有過性幻想嗎？", level: 5 },
    { id: "ad_t_25", text: "你覺得在場誰的身材最好？", level: 4 },
    { id: "ad_t_26", text: "你曾經拍過裸照嗎？", level: 5 },
    { id: "ad_t_27", text: "你曾經使用過交友軟體約炮嗎？", level: 5 },
    { id: "ad_t_28", text: "你最尷尬的一次性經驗？", level: 5 },
    { id: "ad_t_29", text: "你曾經被劈腿過嗎？", level: 4 },
    { id: "ad_t_30", text: "你曾經當過第三者嗎？", level: 5 },
    { id: "ad_t_31", text: "你喜歡開燈還是關燈？", level: 4 },
    { id: "ad_t_32", text: "你曾經在野外（非室內）做過嗎？", level: 5 },
    { id: "ad_t_33", text: "你覺得尺寸重要嗎？", level: 5 },
    { id: "ad_t_34", text: "你曾經假裝高潮過幾次？", level: 5 },
    { id: "ad_t_35", text: "你曾經對老師有過性幻想嗎？", level: 4 },
    { id: "ad_t_36", text: "你最喜歡的前戲是什麼？", level: 5 },
    {
      id: "ad_t_37",
      text: "你曾經在看電影時做過羞羞的事嗎？",
      level: 5,
    },
    { id: "ad_t_38", text: "你曾經懷疑過自己的性向嗎？", level: 4 },
    { id: "ad_t_39", text: "你曾經和同性接吻過嗎？", level: 4 },
    { id: "ad_t_40", text: "你覺得在場誰最色？", level: 4 },
    { id: "ad_t_41", text: "你曾經在視訊時做過嗎？", level: 5 },
    { id: "ad_t_42", text: "你曾經買過情趣用品嗎？", level: 4 },
    { id: "ad_t_43", text: "你曾經在朋友家做過嗎？", level: 5 },
    { id: "ad_t_44", text: "你最喜歡的角色扮演是什麼？", level: 5 },
    { id: "ad_t_45", text: "你曾經因為性生活不合而分手嗎？", level: 5 },
    { id: "ad_t_46", text: "你曾經在海邊做過嗎？", level: 5 },
    { id: "ad_t_47", text: "你覺得自己是攻還是受？", level: 4 },
    { id: "ad_t_48", text: "你曾經被父母撞見過嗎？", level: 6 },
    { id: "ad_t_49", text: "你曾經同時喜歡上兩個人嗎？", level: 4 },
    { id: "ad_t_50", text: "你曾經為了錢出賣過肉體嗎？", level: 6 },
  ],
  dare: [
    { id: "ad_d_01", text: "脫掉一件衣物（配件不算）。", level: 4 },
    { id: "ad_d_02", text: "發出高潮時的聲音，越大聲越好。", level: 5 },
    { id: "ad_d_03", text: "選一位異性，深情對視 30 秒。", level: 4 },
    { id: "ad_d_04", text: "讓在場的人檢查你的瀏覽器紀錄。", level: 5 },
    { id: "ad_d_05", text: "親吻坐在你右邊的人的脖子。", level: 5 },
    {
      id: "ad_d_06",
      text: "表演一段性感的鋼管舞（用椅子代替）。",
      level: 4,
    },
    { id: "ad_d_07", text: "喝一杯酒（或特調飲料）。", level: 3 },
    {
      id: "ad_d_08",
      text: "讓一位異性坐在你的大腿上持續一回合。",
      level: 5,
    },
    { id: "ad_d_09", text: "用嘴巴傳遞冰塊給下一個人。", level: 5 },
    {
      id: "ad_d_10",
      text: "隨機撥打一位異性朋友電話，呻吟一聲後掛斷。",
      level: 6,
    },
    {
      id: "ad_d_11",
      text: "讓大家看你手機裡最性感的一張照片。",
      level: 4,
    },
    { id: "ad_d_12", text: "模仿一種性愛姿勢。", level: 5 },
    {
      id: "ad_d_13",
      text: "讓左邊的人在你的鎖骨上種草莓（或畫口紅印）。",
      level: 5,
    },
    { id: "ad_d_14", text: "舔一下坐在你對面的人的耳朵。", level: 6 },
    {
      id: "ad_d_15",
      text: "用嘴巴解開某人的鈕扣（如果有的話）。",
      level: 5,
    },
    { id: "ad_d_16", text: "對著一位玩家跳電臀舞。", level: 4 },
    { id: "ad_d_17", text: "含著一口水，讓大家逗你笑。", level: 3 },
    { id: "ad_d_18", text: "展示你現在穿的內褲顏色。", level: 4 },
    {
      id: "ad_d_19",
      text: "用誘惑的聲音讀出一段說明書文字。",
      level: 4,
    },
    {
      id: "ad_d_20",
      text: "讓一位玩家把手伸進你的衣服裡暖手 10 秒。",
      level: 5,
    },
    { id: "ad_d_21", text: "親吻右邊玩家的手背。", level: 4 },
    { id: "ad_d_22", text: "讓左邊玩家打你的屁股一下。", level: 4 },
    { id: "ad_d_23", text: "用嘴巴咬住一根香蕉並吃掉。", level: 5 },
    { id: "ad_d_24", text: "對著鏡頭做出高潮臉。", level: 5 },
    { id: "ad_d_25", text: "讓一位異性幫你塗護唇膏。", level: 4 },
    { id: "ad_d_26", text: "在一位異性耳邊吹氣。", level: 5 },
    {
      id: "ad_d_27",
      text: "用舌頭舔一下自己的嘴唇，做出誘惑表情。",
      level: 4,
    },
    {
      id: "ad_d_28",
      text: "讓大家看你手機裡最近的一張自拍。",
      level: 3,
    },
    { id: "ad_d_29", text: "模仿A片裡的經典台詞。", level: 5 },
    {
      id: "ad_d_30",
      text: "讓一位異性摸你的腹肌（或肚子）。",
      level: 4,
    },
    { id: "ad_d_31", text: "喝下一杯混酒。", level: 4 },
    { id: "ad_d_32", text: "用嘴巴從桌上咬起一支筆。", level: 3 },
    {
      id: "ad_d_33",
      text: "讓右邊的人坐在你背上做伏地挺身。",
      level: 4,
    },
    { id: "ad_d_34", text: "對著一位異性壁咚。", level: 4 },
    { id: "ad_d_35", text: "用嘴巴餵左邊的人吃東西。", level: 5 },
    { id: "ad_d_36", text: "讓大家看你的搜尋紀錄。", level: 5 },
    { id: "ad_d_37", text: "模仿脫衣舞孃的動作。", level: 5 },
    { id: "ad_d_38", text: "讓一位異性聞你的脖子。", level: 5 },
    {
      id: "ad_d_39",
      text: "用性感的聲音點餐（假裝打電話）。",
      level: 4,
    },
    { id: "ad_d_40", text: "讓大家看你追蹤的IG正妹/帥哥。", level: 4 },
    { id: "ad_d_41", text: "親吻左邊玩家的臉頰。", level: 4 },
    { id: "ad_d_42", text: "讓右邊玩家幫你按摩大腿。", level: 5 },
    { id: "ad_d_43", text: "用嘴巴解開自己的皮帶。", level: 5 },
    { id: "ad_d_44", text: "對著一位異性跳一段貼身舞。", level: 5 },
    {
      id: "ad_d_45",
      text: "讓大家看你手機裡最私密的一張照片（不一定要裸露）。",
      level: 5,
    },
    { id: "ad_d_46", text: "模仿高潮時的表情自拍。", level: 5 },
    { id: "ad_d_47", text: "讓一位異性幫你脫襪子。", level: 4 },
    { id: "ad_d_48", text: "用舌頭寫出自己的名字。", level: 4 },
    { id: "ad_d_49", text: "讓左邊的人檢查你的內衣顏色。", level: 5 },
    { id: "ad_d_50", text: "大喊「我好想要」三聲。", level: 5 },
  ],
};
