window.defaultGameData = window.defaultGameData || {};
window.defaultGameData["生死之交"] = {
  // Bestie (Level 3-5) - 秘密、吐槽、友情考驗
  truth: [
    {
      id: "be_t_01",
      text: "在場的人之中，你最不喜歡誰的穿衣風格？",
      level: 3,
    },
    { id: "be_t_02", text: "你曾經在背後說過在場誰的壞話？", level: 4 },
    {
      id: "be_t_03",
      text: "你覺得在場誰最可能會單身一輩子？",
      level: 3,
    },
    { id: "be_t_04", text: "你曾經嫉妒過在場的誰？為什麼？", level: 3 },
    {
      id: "be_t_05",
      text: "如果你必須絕交一個人，你會選誰？",
      level: 4,
    },
    { id: "be_t_06", text: "你覺得誰的戀愛眼光最差？", level: 3 },
    {
      id: "be_t_07",
      text: "分享一個你從未告訴過任何人的秘密。",
      level: 4,
    },
    { id: "be_t_08", text: "你借過錢給誰但對方沒還？", level: 3 },
    { id: "be_t_09", text: "你覺得在場誰最虛偽？", level: 5 },
    { id: "be_t_10", text: "你上次說謊騙朋友是為了什麼？", level: 3 },
    { id: "be_t_11", text: "你覺得誰最重色輕友？", level: 3 },
    {
      id: "be_t_12",
      text: "你曾經喜歡過朋友的男/女朋友嗎？",
      level: 4,
    },
    { id: "be_t_13", text: "在場誰的秘密你知道最多？", level: 2 },
    { id: "be_t_14", text: "你覺得誰最需要看心理醫生？", level: 3 },
    {
      id: "be_t_15",
      text: "如果我們都愛上同一個人，你會退出嗎？",
      level: 3,
    },
    { id: "be_t_16", text: "你覺得在場誰最愛記仇？", level: 3 },
    {
      id: "be_t_17",
      text: "你曾經想過要跟在場的誰斷絕關係？",
      level: 5,
    },
    { id: "be_t_18", text: "你覺得在場誰最容易被騙？", level: 3 },
    { id: "be_t_19", text: "你覺得誰的脾氣最差？", level: 3 },
    {
      id: "be_t_20",
      text: "你曾經偷看過朋友的日記或訊息嗎？",
      level: 4,
    },
    { id: "be_t_21", text: "你覺得在場誰最自戀？", level: 3 },
    { id: "be_t_22", text: "你曾經討厭過在場的誰？", level: 4 },
    { id: "be_t_23", text: "你覺得誰最愛裝熟？", level: 3 },
    { id: "be_t_24", text: "你覺得誰最不守信用？", level: 3 },
    { id: "be_t_25", text: "你曾經把朋友的秘密說出去過嗎？", level: 5 },
    { id: "be_t_26", text: "你覺得在場誰最愛炫耀？", level: 3 },
    { id: "be_t_27", text: "你覺得誰最容易出軌？", level: 4 },
    {
      id: "be_t_28",
      text: "你曾經借給朋友東西但不想還他嗎？",
      level: 3,
    },
    { id: "be_t_29", text: "你覺得誰最愛遲到？", level: 2 },
    { id: "be_t_30", text: "你覺得誰最愛佔小便宜？", level: 3 },
    { id: "be_t_31", text: "你曾經對朋友的另一半有意見嗎？", level: 4 },
    { id: "be_t_32", text: "你覺得誰最愛八卦？", level: 3 },
    { id: "be_t_33", text: "你覺得誰最難相處？", level: 4 },
    { id: "be_t_34", text: "你曾經故意不回朋友訊息嗎？", level: 3 },
    { id: "be_t_35", text: "你覺得誰最愛哭？", level: 2 },
    { id: "be_t_36", text: "你覺得誰最沒主見？", level: 3 },
    { id: "be_t_37", text: "你曾經封鎖過在場的誰嗎？", level: 5 },
    { id: "be_t_38", text: "你覺得誰最愛喝酒？", level: 2 },
    { id: "be_t_39", text: "你覺得誰最愛抱怨？", level: 3 },
    { id: "be_t_40", text: "你覺得誰最愛管閒事？", level: 3 },
    { id: "be_t_41", text: "你曾經跟朋友喜歡上同一個人嗎？", level: 4 },
    { id: "be_t_42", text: "你覺得誰最愛裝可憐？", level: 4 },
    { id: "be_t_43", text: "你覺得誰最愛搶風頭？", level: 3 },
    { id: "be_t_44", text: "你曾經因為錢跟朋友吵架嗎？", level: 4 },
    { id: "be_t_45", text: "你覺得誰最愛說謊？", level: 4 },
    { id: "be_t_46", text: "你覺得誰最愛放鴿子？", level: 3 },
    { id: "be_t_47", text: "你覺得誰最愛借錢？", level: 3 },
    { id: "be_t_48", text: "你曾經覺得朋友很煩嗎？", level: 4 },
    { id: "be_t_49", text: "你覺得誰最愛裝忙？", level: 3 },
    { id: "be_t_50", text: "你覺得誰是你真正的最好的朋友？", level: 3 },
  ],
  dare: [
    {
      id: "be_d_01",
      text: "交出手機，讓大家隨意挑選一條訊息朗讀。",
      level: 4,
    },
    { id: "be_d_02", text: "給前任傳訊息說「我還想你」。", level: 5 },
    {
      id: "be_d_03",
      text: "在社群媒體發一張超醜的自拍，並標註「這就是真實的我」。",
      level: 4,
    },
    {
      id: "be_d_04",
      text: "讓在場的人翻閱你的相簿 1 分鐘。",
      level: 4,
    },
    {
      id: "be_d_05",
      text: "打電話給父母說「我懷孕了/讓人懷孕了」。",
      level: 5,
    },
    { id: "be_d_06", text: "模仿在場某個人的缺點。", level: 3 },
    {
      id: "be_d_07",
      text: "讓大家看你和最近聊天對象的對話紀錄。",
      level: 4,
    },
    {
      id: "be_d_08",
      text: "對著在場一個人深情告白 1 分鐘。",
      level: 3,
    },
    {
      id: "be_d_09",
      text: "喝下一杯大家特製的「地獄飲料」。",
      level: 4,
    },
    {
      id: "be_d_10",
      text: "把你的手機桌布換成在場某人的醜照。",
      level: 3,
    },
    { id: "be_d_11", text: "大聲朗讀你最近的一則備忘錄。", level: 3 },
    { id: "be_d_12", text: "讓右邊的人用口紅在你臉上畫畫。", level: 3 },
    { id: "be_d_13", text: "公主抱左邊的人深蹲 5 下。", level: 3 },
    { id: "be_d_14", text: "隨機打給一個朋友借 5000 元。", level: 4 },
    {
      id: "be_d_15",
      text: "讓大家看你的網購購物車或搜尋紀錄。",
      level: 4,
    },
    { id: "be_d_16", text: "打電話給一個朋友說你中樂透了。", level: 4 },
    {
      id: "be_d_17",
      text: "讓大家看你手機裡最舊的一張照片。",
      level: 3,
    },
    { id: "be_d_18", text: "模仿在場某人喝醉的樣子。", level: 3 },
    {
      id: "be_d_19",
      text: "讓右邊的人幫你發一則IG限時動態。",
      level: 4,
    },
    {
      id: "be_d_20",
      text: "隨機打給通訊錄裡的一個人唱生日快樂歌。",
      level: 4,
    },
    { id: "be_d_21", text: "讓大家看你的YouTube觀看紀錄。", level: 4 },
    {
      id: "be_d_22",
      text: "把你的LINE大頭貼換成鬼臉照一天。",
      level: 4,
    },
    {
      id: "be_d_23",
      text: "讓左邊的人幫你綁頭髮（或弄亂頭髮）。",
      level: 2,
    },
    { id: "be_d_24", text: "對著鏡頭說出三個自己的缺點。", level: 3 },
    { id: "be_d_25", text: "讓大家看你封鎖的名單。", level: 5 },
    {
      id: "be_d_26",
      text: "隨機傳一張貼圖給最近聊天的三個人。",
      level: 3,
    },
    { id: "be_d_27", text: "讓右邊的人幫你選一件衣服脫掉。", level: 4 },
    { id: "be_d_28", text: "模仿在場某人笑的聲音。", level: 3 },
    { id: "be_d_29", text: "讓大家看你錢包裡的照片。", level: 3 },
    { id: "be_d_30", text: "打電話給媽媽說「我愛你」。", level: 2 },
    {
      id: "be_d_31",
      text: "讓左邊的人在你手臂上畫一隻烏龜。",
      level: 2,
    },
    {
      id: "be_d_32",
      text: "大聲唸出你最近搜尋的三個關鍵字。",
      level: 4,
    },
    { id: "be_d_33", text: "讓大家看你手機裡最尷尬的影片。", level: 4 },
    { id: "be_d_34", text: "隨機打給一個異性朋友約吃飯。", level: 4 },
    { id: "be_d_35", text: "讓右邊的人幫你回覆一則訊息。", level: 4 },
    { id: "be_d_36", text: "模仿在場某人走路的樣子。", level: 3 },
    {
      id: "be_d_37",
      text: "讓大家看你的Google Map搜尋紀錄。",
      level: 3,
    },
    { id: "be_d_38", text: "隨機傳「我好寂寞」給一個朋友。", level: 5 },
    {
      id: "be_d_39",
      text: "讓左邊的人幫你擦指甲油（或畫指甲）。",
      level: 2,
    },
    { id: "be_d_40", text: "對著窗外大喊「我是笨蛋」。", level: 3 },
    {
      id: "be_d_41",
      text: "讓大家看你手機裡最不想被看到的App。",
      level: 4,
    },
    { id: "be_d_42", text: "隨機打給一個朋友說笑話。", level: 3 },
    { id: "be_d_43", text: "讓右邊的人幫你按摩頭皮。", level: 2 },
    { id: "be_d_44", text: "模仿在場某人自拍的姿勢。", level: 3 },
    { id: "be_d_45", text: "讓大家看你的蝦皮購物車。", level: 3 },
    {
      id: "be_d_46",
      text: "隨機傳一張自拍給最近聊天的異性。",
      level: 4,
    },
    { id: "be_d_47", text: "讓左邊的人幫你畫眉毛。", level: 3 },
    { id: "be_d_48", text: "對著鏡頭做鬼臉五連拍。", level: 2 },
    {
      id: "be_d_49",
      text: "讓大家看你手機裡最久以前的照片。",
      level: 3,
    },
    { id: "be_d_50", text: "大聲說出在場你最喜歡的人。", level: 4 },
  ],
};
