window.defaultGameData = window.defaultGameData || {};
window.defaultGameData["普通朋友"] = {
  // Casual (Level 1-3) - 適合破冰、一般聚會
  truth: [
    {
      id: "ca_t_01",
      text: "如果能擁有一項超能力，你會選什麼？",
      level: 1,
    },
    {
      id: "ca_t_02",
      text: "你最喜歡的電影是哪一部？為什麼？",
      level: 1,
    },
    {
      id: "ca_t_03",
      text: "如果中了一億元，你第一件事會做什麼？",
      level: 1,
    },
    { id: "ca_t_04", text: "你小時候的夢想職業是什麼？", level: 1 },
    { id: "ca_t_05", text: "分享一件你最近發生的糗事。", level: 2 },
    { id: "ca_t_06", text: "在場的人之中，你覺得誰最有趣？", level: 2 },
    { id: "ca_t_07", text: "你最害怕的一種動物是什麼？", level: 1 },
    {
      id: "ca_t_08",
      text: "如果可以和世界上任何人共進晚餐，你會選誰？",
      level: 1,
    },
    {
      id: "ca_t_09",
      text: "你人生中做過最勇敢的事情是什麼？",
      level: 2,
    },
    { id: "ca_t_10", text: "你有什麼奇怪的癖好嗎？", level: 2 },
    { id: "ca_t_11", text: "你最近一次哭是因為什麼？", level: 2 },
    {
      id: "ca_t_12",
      text: "如果明天是世界末日，你會怎麼度過？",
      level: 2,
    },
    { id: "ca_t_13", text: "你最討厭的一種食物是什麼？", level: 1 },
    { id: "ca_t_14", text: "分享一個你童年的秘密基地。", level: 1 },
    {
      id: "ca_t_15",
      text: "你曾經對朋友說過最大的謊是什麼？",
      level: 3,
    },
    {
      id: "ca_t_16",
      text: "如果必須在場選一個人去荒島，你會選誰？",
      level: 2,
    },
    { id: "ca_t_17", text: "你最想去哪個國家旅遊？", level: 1 },
    { id: "ca_t_18", text: "你覺得自己最大的優點是什麼？", level: 1 },
    { id: "ca_t_19", text: "你上一次生氣是因為什麼？", level: 2 },
    {
      id: "ca_t_20",
      text: "如果可以回到過去，你最想改變哪一件事？",
      level: 2,
    },
    { id: "ca_t_21", text: "你最喜歡的一首歌是什麼？", level: 1 },
    { id: "ca_t_22", text: "你相信有外星人嗎？", level: 1 },
    { id: "ca_t_23", text: "你最想學會哪種語言？", level: 1 },
    {
      id: "ca_t_24",
      text: "你睡覺前最後一件事通常是做什麼？",
      level: 1,
    },
    { id: "ca_t_25", text: "你覺得自己像哪種動物？", level: 1 },
    { id: "ca_t_26", text: "你最喜歡的季節是？為什麼？", level: 1 },
    { id: "ca_t_27", text: "你曾經在公共場合跌倒過嗎？", level: 2 },
    { id: "ca_t_28", text: "你最喜歡的節日是哪一個？", level: 1 },
    { id: "ca_t_29", text: "你覺得錢能買到快樂嗎？", level: 2 },
    { id: "ca_t_30", text: "你最想嘗試的極限運動是什麼？", level: 1 },
    { id: "ca_t_31", text: "你曾經為了逃避做某事而裝病嗎？", level: 2 },
    { id: "ca_t_32", text: "你最喜歡的冰淇淋口味？", level: 1 },
    { id: "ca_t_33", text: "你覺得男女之間有純友誼嗎？", level: 2 },
    { id: "ca_t_34", text: "你最近看的一本書是什麼？", level: 1 },
    { id: "ca_t_35", text: "你曾經在電梯裡放屁嗎？", level: 2 },
    { id: "ca_t_36", text: "你最喜歡自己身體的哪個部位？", level: 2 },
    { id: "ca_t_37", text: "如果可以隱形一天，你會做什麼？", level: 2 },
    { id: "ca_t_38", text: "你曾經網戀過嗎？", level: 2 },
    { id: "ca_t_39", text: "你覺得自己是樂觀還是悲觀的人？", level: 1 },
    { id: "ca_t_40", text: "你最害怕失去什麼？", level: 2 },
    { id: "ca_t_41", text: "你曾經偷拿過別人的東西嗎？", level: 3 },
    { id: "ca_t_42", text: "你覺得自己會是個好父母嗎？", level: 2 },
    { id: "ca_t_43", text: "你最想見到的已故名人是誰？", level: 1 },
    { id: "ca_t_44", text: "你曾經被狗追過嗎？", level: 1 },
    { id: "ca_t_45", text: "你最喜歡的YouTuber是誰？", level: 1 },
    { id: "ca_t_46", text: "你曾經在考試中作弊嗎？", level: 2 },
    { id: "ca_t_47", text: "你覺得什麼樣的異性最吸引你？", level: 2 },
    { id: "ca_t_48", text: "你曾經因為看電影而哭嗎？", level: 1 },
    { id: "ca_t_49", text: "你最想住在城市還是鄉下？", level: 1 },
    { id: "ca_t_50", text: "分享一個你最近的小確幸。", level: 1 },
  ],
  dare: [
    {
      id: "ca_d_01",
      text: "模仿一種動物的叫聲，持續 10 秒。",
      level: 1,
    },
    { id: "ca_d_02", text: "做 10 個伏地挺身。", level: 2 },
    { id: "ca_d_03", text: "讓坐在你右邊的人幫你整理頭髮。", level: 1 },
    {
      id: "ca_d_04",
      text: "用屁股寫字，讓大家猜你在寫什麼。",
      level: 2,
    },
    {
      id: "ca_d_05",
      text: "對窗外大喊：「我是超級大帥哥/美女！」。",
      level: 2,
    },
    { id: "ca_d_06", text: "模仿在場某個人的說話方式。", level: 2 },
    { id: "ca_d_07", text: "閉著眼睛畫一隻豬。", level: 1 },
    {
      id: "ca_d_08",
      text: "讓大家看你手機裡最近的一張照片。",
      level: 2,
    },
    { id: "ca_d_09", text: "用奇怪的口音說話直到下一回合。", level: 2 },
    { id: "ca_d_10", text: "聞坐在你左邊的人的襪子。", level: 3 },
    { id: "ca_d_11", text: "表演一段空氣吉他獨奏。", level: 1 },
    { id: "ca_d_12", text: "讓在場每個人摸一下你的頭。", level: 1 },
    { id: "ca_d_13", text: "學貓叫三聲，要很撒嬌的那種。", level: 2 },
    {
      id: "ca_d_14",
      text: "用你的鼻子觸碰你的舌頭（如果做不到就做鬼臉）。",
      level: 1,
    },
    {
      id: "ca_d_15",
      text: "隨機撥打通訊錄的一個人說「祝你今天愉快」。",
      level: 3,
    },
    { id: "ca_d_16", text: "模仿名模走台步繞場一周。", level: 2 },
    { id: "ca_d_17", text: "保持笑容持續一分鐘。", level: 1 },
    { id: "ca_d_18", text: "背一位玩家繞場一圈。", level: 3 },
    {
      id: "ca_d_19",
      text: "用左手（非慣用手）寫下自己的名字。",
      level: 1,
    },
    { id: "ca_d_20", text: "自拍一張最醜的鬼臉照並展示。", level: 2 },
    { id: "ca_d_21", text: "鬥雞眼持續 10 秒。", level: 1 },
    { id: "ca_d_22", text: "模仿一種樂器的聲音。", level: 1 },
    {
      id: "ca_d_23",
      text: "讓右邊的人幫你塗口紅（或畫鬍子）。",
      level: 2,
    },
    { id: "ca_d_24", text: "用慢動作做所有事情持續一回合。", level: 2 },
    { id: "ca_d_25", text: "對著牆壁深情告白 30 秒。", level: 2 },
    { id: "ca_d_26", text: "把鞋子脫掉直到下一回合。", level: 1 },
    { id: "ca_d_27", text: "模仿猴子抓癢的動作。", level: 1 },
    { id: "ca_d_28", text: "讓大家看你錢包裡有多少錢。", level: 2 },
    { id: "ca_d_29", text: "用膝蓋夾著一張紙走一圈。", level: 2 },
    { id: "ca_d_30", text: "模仿殭屍跳。", level: 1 },
    { id: "ca_d_31", text: "讓左邊的人搔你癢 10 秒不能笑。", level: 2 },
    { id: "ca_d_32", text: "用RAP的方式自我介紹。", level: 2 },
    { id: "ca_d_33", text: "把頭髮弄成最亂的樣子。", level: 1 },
    { id: "ca_d_34", text: "模仿一位政治人物。", level: 2 },
    { id: "ca_d_35", text: "用屁股撞坐在你兩邊的人。", level: 2 },
    { id: "ca_d_36", text: "含著水唱一首歌。", level: 3 },
    { id: "ca_d_37", text: "讓大家看你手機的螢幕使用時間。", level: 2 },
    { id: "ca_d_38", text: "模仿嬰兒哭聲。", level: 1 },
    { id: "ca_d_39", text: "做 5 個深蹲。", level: 1 },
    { id: "ca_d_40", text: "用手肘打字傳訊息給一個人。", level: 2 },
    { id: "ca_d_41", text: "聞自己的腋下。", level: 2 },
    { id: "ca_d_42", text: "模仿雞走路繞場一圈。", level: 1 },
    {
      id: "ca_d_43",
      text: "讓右邊的人在你額頭上貼一張便利貼。",
      level: 1,
    },
    { id: "ca_d_44", text: "用歌劇的方式說話持續一回合。", level: 2 },
    { id: "ca_d_45", text: "假裝自己在騎馬。", level: 1 },
    {
      id: "ca_d_46",
      text: "對著鏡頭（或鏡子）擺出三個性感姿勢。",
      level: 2,
    },
    { id: "ca_d_47", text: "讓大家檢查你的包包。", level: 3 },
    { id: "ca_d_48", text: "模仿魚嘴巴開合 10 次。", level: 1 },
    { id: "ca_d_49", text: "用頭頂著一個杯子持續一回合。", level: 2 },
    { id: "ca_d_50", text: "大喊「我是笨蛋」三聲。", level: 2 },
  ],
};
