window.defaultGameData = window.defaultGameData || {};
window.defaultGameData["合家歡樂"] = {
  // Family (Level 1) - 安全、溫馨、老少咸宜
  truth: [
    { id: "fa_t_01", text: "你最喜歡家裡煮的哪一道菜？", level: 1 },
    { id: "fa_t_02", text: "小時候你最喜歡的玩具是什麼？", level: 1 },
    { id: "fa_t_03", text: "分享一個你小時候的糗事。", level: 1 },
    { id: "fa_t_04", text: "你覺得家裡誰最愛睡覺？", level: 1 },
    {
      id: "fa_t_05",
      text: "如果全家一起去旅遊，你最想去哪裡？",
      level: 1,
    },
    { id: "fa_t_06", text: "你最喜歡的一部卡通是什麼？", level: 1 },
    { id: "fa_t_07", text: "你覺得自己長得像爸爸還是媽媽？", level: 1 },
    { id: "fa_t_08", text: "說出三個你最喜歡的零食。", level: 1 },
    { id: "fa_t_09", text: "你最不喜歡做的家事是什麼？", level: 1 },
    { id: "fa_t_10", text: "分享一件讓你覺得很幸福的事。", level: 1 },
    { id: "fa_t_11", text: "你最喜歡學校的哪一門課？", level: 1 },
    {
      id: "fa_t_12",
      text: "如果可以養任何動物，你想養什麼？",
      level: 1,
    },
    { id: "fa_t_13", text: "你覺得誰是家裡的開心果？", level: 1 },
    { id: "fa_t_14", text: "你最怕什麼昆蟲？", level: 1 },
    { id: "fa_t_15", text: "說出一個你最好的朋友的名字。", level: 1 },
    { id: "fa_t_16", text: "你最喜歡什麼顏色？", level: 1 },
    {
      id: "fa_t_17",
      text: "如果可以不用上學/上班，你想做什麼？",
      level: 1,
    },
    { id: "fa_t_18", text: "你最喜歡的迪士尼角色是誰？", level: 1 },
    { id: "fa_t_19", text: "你覺得家裡誰最會煮飯？", level: 1 },
    { id: "fa_t_20", text: "你最喜歡的水果是什麼？", level: 1 },
    { id: "fa_t_21", text: "你曾經打破過家裡的東西嗎？", level: 1 },
    { id: "fa_t_22", text: "你最喜歡的運動是什麼？", level: 1 },
    {
      id: "fa_t_23",
      text: "如果可以變成一種動物，你想變什麼？",
      level: 1,
    },
    { id: "fa_t_24", text: "你最喜歡的節日是哪一個？", level: 1 },
    { id: "fa_t_25", text: "你覺得家裡誰最愛碎碎念？", level: 1 },
    { id: "fa_t_26", text: "你最喜歡的一本書是什麼？", level: 1 },
    {
      id: "fa_t_27",
      text: "你長大後想做什麼？（或小時候想做什麼）",
      level: 1,
    },
    { id: "fa_t_28", text: "你最喜歡的甜點是什麼？", level: 1 },
    { id: "fa_t_29", text: "你覺得誰最會唱歌？", level: 1 },
    { id: "fa_t_30", text: "你最喜歡去哪裡玩？", level: 1 },
    { id: "fa_t_31", text: "你曾經考過最差的分數是多少？", level: 1 },
    { id: "fa_t_32", text: "你最喜歡的飲料是什麼？", level: 1 },
    { id: "fa_t_33", text: "你覺得家裡誰最聰明？", level: 1 },
    { id: "fa_t_34", text: "你最喜歡的季節？", level: 1 },
    { id: "fa_t_35", text: "你曾經偷偷把菜丟掉嗎？", level: 1 },
    { id: "fa_t_36", text: "你最喜歡的桌遊或遊戲是什麼？", level: 1 },
    { id: "fa_t_37", text: "你覺得聖誕老公公是真的嗎？", level: 1 },
    { id: "fa_t_38", text: "你最喜歡的早餐是什麼？", level: 1 },
    { id: "fa_t_39", text: "你覺得家裡誰最愛看電視？", level: 1 },
    { id: "fa_t_40", text: "你最想學會什麼才藝？", level: 1 },
    { id: "fa_t_41", text: "你最喜歡的超級英雄是誰？", level: 1 },
    { id: "fa_t_42", text: "你曾經在床上尿床嗎？", level: 1 },
    { id: "fa_t_43", text: "你最喜歡的冰淇淋口味？", level: 1 },
    { id: "fa_t_44", text: "你覺得家裡誰最愛乾淨？", level: 1 },
    { id: "fa_t_45", text: "你最喜歡的一首歌？", level: 1 },
    { id: "fa_t_46", text: "你最喜歡去動物園看什麼動物？", level: 1 },
    { id: "fa_t_47", text: "你覺得家裡誰最搞笑？", level: 1 },
    { id: "fa_t_48", text: "你最喜歡的披薩口味？", level: 1 },
    { id: "fa_t_49", text: "你曾經撿到錢嗎？", level: 1 },
    { id: "fa_t_50", text: "你最愛的人是誰？", level: 1 },
  ],
  dare: [
    {
      id: "fa_d_01",
      text: "給坐在你右邊的人一個大大的擁抱。",
      level: 1,
    },
    { id: "fa_d_02", text: "唱一首兒歌給大家聽。", level: 1 },
    { id: "fa_d_03", text: "做一個最滑稽的鬼臉。", level: 1 },
    { id: "fa_d_04", text: "模仿猴子的動作繞桌子一圈。", level: 1 },
    { id: "fa_d_05", text: "說一個笑話讓大家笑。", level: 1 },
    { id: "fa_d_06", text: "用屁股寫你的名字。", level: 1 },
    { id: "fa_d_07", text: "頂著一本書在頭上走直線。", level: 1 },
    {
      id: "fa_d_08",
      text: "和左邊的人猜拳，輸的人要學狗叫。",
      level: 1,
    },
    { id: "fa_d_09", text: "閉著眼睛摸一樣東西並猜是什麼。", level: 1 },
    { id: "fa_d_10", text: "跳一段自創的舞。", level: 1 },
    { id: "fa_d_11", text: "模仿機器人說話。", level: 1 },
    { id: "fa_d_12", text: "幫右邊的人搥背 10 下。", level: 1 },
    { id: "fa_d_13", text: "用鼻子畫一個圈。", level: 1 },
    { id: "fa_d_14", text: "大笑三聲「哈！哈！哈！」。", level: 1 },
    { id: "fa_d_15", text: "做 5 個開合跳。", level: 1 },
    { id: "fa_d_16", text: "模仿大象鼻子轉圈圈。", level: 1 },
    { id: "fa_d_17", text: "用屁股撞一下左邊的人。", level: 1 },
    { id: "fa_d_18", text: "學貓咪洗臉的動作。", level: 1 },
    { id: "fa_d_19", text: "單腳站立 10 秒。", level: 1 },
    { id: "fa_d_20", text: "模仿爸爸或媽媽生氣的樣子。", level: 1 },
    { id: "fa_d_21", text: "用手當望遠鏡看大家。", level: 1 },
    { id: "fa_d_22", text: "學鴨子走路。", level: 1 },
    { id: "fa_d_23", text: "對著大家飛吻。", level: 1 },
    { id: "fa_d_24", text: "模仿時鐘的指針動作。", level: 1 },
    { id: "fa_d_25", text: "用慢動作High Five。", level: 1 },
    { id: "fa_d_26", text: "學青蛙跳三下。", level: 1 },
    {
      id: "fa_d_27",
      text: "用肚子頂一顆球（或枕頭）走一圈。",
      level: 1,
    },
    { id: "fa_d_28", text: "模仿睡覺打呼的聲音。", level: 1 },
    {
      id: "fa_d_29",
      text: "跟右邊的人握手說「你好帥/美」。",
      level: 1,
    },
    { id: "fa_d_30", text: "做一個超人飛行的姿勢。", level: 1 },
    { id: "fa_d_31", text: "模仿企鵝走路。", level: 1 },
    { id: "fa_d_32", text: "用手比一個愛心送給大家。", level: 1 },
    { id: "fa_d_33", text: "學恐龍叫。", level: 1 },
    { id: "fa_d_34", text: "轉圈圈三圈然後擺Pose。", level: 1 },
    { id: "fa_d_35", text: "模仿正在吃很酸的檸檬。", level: 1 },
    { id: "fa_d_36", text: "跟左邊的人玩「黑白配」。", level: 1 },
    { id: "fa_d_37", text: "用屁股寫數字 1 到 5。", level: 1 },
    { id: "fa_d_38", text: "模仿兔子跳。", level: 1 },
    { id: "fa_d_39", text: "假裝自己在開車。", level: 1 },
    { id: "fa_d_40", text: "摸摸自己的鼻子再摸摸耳朵。", level: 1 },
    { id: "fa_d_41", text: "學老爺爺/老奶奶走路。", level: 1 },
    { id: "fa_d_42", text: "假裝自己在游泳。", level: 1 },
    { id: "fa_d_43", text: "用膝蓋碰手肘。", level: 1 },
    { id: "fa_d_44", text: "模仿一種樂器演奏。", level: 1 },
    { id: "fa_d_45", text: "做一個鬼臉自拍。", level: 1 },
    { id: "fa_d_46", text: "學公雞叫大家起床。", level: 1 },
    { id: "fa_d_47", text: "假裝自己在彈鋼琴。", level: 1 },
    { id: "fa_d_48", text: "用手做一個眼鏡戴上。", level: 1 },
    { id: "fa_d_49", text: "模仿殭屍跳。", level: 1 },
    { id: "fa_d_50", text: "大聲說「我愛我的家」！", level: 1 },
  ],
};
