window.defaultGameData = window.defaultGameData || {};
window.defaultGameData["感情鑑定"] = {
  // Couple (Level 3-5) - 情侶專屬、深入話題
  truth: [
    {
      id: "cp_t_01",
      text: "你第一次見到我時，對我的真實印象是什麼？",
      level: 2,
    },
    {
      id: "cp_t_02",
      text: "我有什麼缺點是你一直忍受，但從來沒告訴過我的？",
      level: 4,
    },
    {
      id: "cp_t_03",
      text: "你覺得我們這段關係最大的問題是什麼？",
      level: 5,
    },
    {
      id: "cp_t_04",
      text: "你曾經動過分手的念頭嗎？什麼時候？",
      level: 5,
    },
    { id: "cp_t_05", text: "你覺得我的家人喜歡你嗎？", level: 3 },
    { id: "cp_t_06", text: "你最喜歡我身體的哪個部位？", level: 3 },
    { id: "cp_t_07", text: "你覺得我們誰付出的比較多？", level: 4 },
    { id: "cp_t_08", text: "你曾經對我說過最大的謊是什麼？", level: 5 },
    { id: "cp_t_09", text: "如果我們分手了，你會怎麼做？", level: 4 },
    { id: "cp_t_10", text: "你覺得我們的性生活美滿嗎？", level: 5 },
    { id: "cp_t_11", text: "你最受不了我哪一點？", level: 4 },
    {
      id: "cp_t_12",
      text: "你覺得我比你的前任好嗎？好在哪裡？",
      level: 5,
    },
    { id: "cp_t_13", text: "你曾經精神出軌過嗎？", level: 5 },
    { id: "cp_t_14", text: "你希望我哪方面可以改進？", level: 3 },
    { id: "cp_t_15", text: "你覺得我們會結婚嗎？", level: 4 },
    { id: "cp_t_16", text: "你最喜歡我穿哪一件衣服？", level: 2 },
    { id: "cp_t_17", text: "你覺得我們誰比較愛吃醋？", level: 3 },
    { id: "cp_t_18", text: "你曾經夢過和其他人在一起嗎？", level: 4 },
    { id: "cp_t_19", text: "你覺得我們誰比較浪漫？", level: 2 },
    { id: "cp_t_20", text: "你最難忘的一次約會是哪一次？", level: 2 },
    { id: "cp_t_21", text: "你覺得我們誰比較會吵架？", level: 3 },
    { id: "cp_t_22", text: "你曾經偷看過我的手機嗎？", level: 4 },
    { id: "cp_t_23", text: "你覺得我們誰比較黏人？", level: 2 },
    { id: "cp_t_24", text: "你最喜歡我的哪一個優點？", level: 2 },
    { id: "cp_t_25", text: "你覺得我們誰比較會花錢？", level: 3 },
    { id: "cp_t_26", text: "你曾經對我的朋友有過好感嗎？", level: 5 },
    { id: "cp_t_27", text: "你覺得我們誰比較會照顧人？", level: 2 },
    { id: "cp_t_28", text: "你最不喜歡我做什麼事？", level: 3 },
    { id: "cp_t_29", text: "你覺得我們誰比較幽默？", level: 2 },
    { id: "cp_t_30", text: "你曾經後悔跟我在一起嗎？", level: 5 },
    { id: "cp_t_31", text: "你覺得我們誰比較聰明？", level: 2 },
    { id: "cp_t_32", text: "你最喜歡我們一起做什麼事？", level: 2 },
    { id: "cp_t_33", text: "你覺得我們誰比較會撒嬌？", level: 2 },
    { id: "cp_t_34", text: "你曾經對我隱瞞過什麼事？", level: 4 },
    { id: "cp_t_35", text: "你覺得我們誰比較會煮飯？", level: 2 },
    { id: "cp_t_36", text: "你最喜歡我叫你什麼？", level: 2 },
    { id: "cp_t_37", text: "你覺得我們誰比較愛乾淨？", level: 2 },
    { id: "cp_t_38", text: "你曾經想過要跟我結婚嗎？", level: 4 },
    { id: "cp_t_39", text: "你覺得我們誰比較會開車？", level: 2 },
    { id: "cp_t_40", text: "你最喜歡我親你哪裡？", level: 3 },
    { id: "cp_t_41", text: "你覺得我們誰比較會打扮？", level: 2 },
    { id: "cp_t_42", text: "你曾經對我失望過嗎？", level: 4 },
    { id: "cp_t_43", text: "你覺得我們誰比較會賺錢？", level: 3 },
    { id: "cp_t_44", text: "你最喜歡我送你的什麼禮物？", level: 2 },
    { id: "cp_t_45", text: "你覺得我們誰比較會睡覺？", level: 2 },
    { id: "cp_t_46", text: "你曾經對我生氣但沒說出來嗎？", level: 3 },
    { id: "cp_t_47", text: "你覺得我們誰比較會運動？", level: 2 },
    { id: "cp_t_48", text: "你最喜歡我煮的哪一道菜？", level: 2 },
    { id: "cp_t_49", text: "你覺得我們誰比較會唱歌？", level: 2 },
    { id: "cp_t_50", text: "你現在有多愛我？（1-10分）", level: 3 },
  ],
  dare: [
    {
      id: "cp_d_01",
      text: "深情對視 1 分鐘，誰先笑誰就輸（脫一件配件）。",
      level: 2,
    },
    { id: "cp_d_02", text: "幫對方按摩肩膀 3 分鐘。", level: 2 },
    { id: "cp_d_03", text: "親吻對方的腳背。", level: 4 },
    { id: "cp_d_04", text: "用嘴巴幫對方脫掉襪子。", level: 3 },
    { id: "cp_d_05", text: "公主抱對方持續 30 秒。", level: 3 },
    { id: "cp_d_06", text: "在對方耳邊說三句最肉麻的情話。", level: 2 },
    { id: "cp_d_07", text: "讓對方檢查你的手機 LINE 訊息。", level: 5 },
    { id: "cp_d_08", text: "跳一支性感的舞給對方看。", level: 4 },
    { id: "cp_d_09", text: "種一個草莓在對方不明顯的地方。", level: 4 },
    { id: "cp_d_10", text: "模仿對方生氣時的樣子。", level: 2 },
    { id: "cp_d_11", text: "用口紅在對方臉上寫「我愛你」。", level: 2 },
    { id: "cp_d_12", text: "交換上衣穿直到下一回合。", level: 3 },
    { id: "cp_d_13", text: "餵對方吃一樣東西（用嘴巴）。", level: 4 },
    {
      id: "cp_d_14",
      text: "大聲喊出「我愛（對方名字）」三次。",
      level: 1,
    },
    { id: "cp_d_15", text: "跪下假裝求婚。", level: 2 },
    { id: "cp_d_16", text: "親吻對方的額頭。", level: 1 },
    { id: "cp_d_17", text: "幫對方剪指甲。", level: 2 },
    { id: "cp_d_18", text: "背著對方繞場一圈。", level: 3 },
    { id: "cp_d_19", text: "用嘴巴餵對方喝水。", level: 3 },
    { id: "cp_d_20", text: "幫對方梳頭髮。", level: 2 },
    { id: "cp_d_21", text: "在對方手心寫字猜字。", level: 2 },
    { id: "cp_d_22", text: "親吻對方的鼻子。", level: 1 },
    { id: "cp_d_23", text: "幫對方塗護唇膏。", level: 2 },
    { id: "cp_d_24", text: "坐在對方大腿上 1 分鐘。", level: 3 },
    { id: "cp_d_25", text: "幫對方按摩小腿。", level: 2 },
    { id: "cp_d_26", text: "親吻對方的耳朵。", level: 3 },
    { id: "cp_d_27", text: "用鼻子磨對方的鼻子。", level: 2 },
    { id: "cp_d_28", text: "幫對方脫鞋子。", level: 2 },
    { id: "cp_d_29", text: "在對方脖子上吹氣。", level: 3 },
    { id: "cp_d_30", text: "幫對方抓癢。", level: 2 },
    { id: "cp_d_31", text: "親吻對方的手心。", level: 2 },
    { id: "cp_d_32", text: "幫對方整理衣服。", level: 1 },
    { id: "cp_d_33", text: "抱著對方轉圈圈。", level: 3 },
    { id: "cp_d_34", text: "用臉頰磨對方的臉頰。", level: 2 },
    { id: "cp_d_35", text: "幫對方擦汗。", level: 2 },
    { id: "cp_d_36", text: "親吻對方的眼睛（閉眼）。", level: 2 },
    { id: "cp_d_37", text: "幫對方戴上飾品。", level: 2 },
    { id: "cp_d_38", text: "握著對方的手深情對視。", level: 2 },
    { id: "cp_d_39", text: "幫對方按摩頭部。", level: 2 },
    { id: "cp_d_40", text: "親吻對方的肩膀。", level: 2 },
    { id: "cp_d_41", text: "幫對方搥背。", level: 2 },
    { id: "cp_d_42", text: "用手指捲對方的頭髮。", level: 2 },
    { id: "cp_d_43", text: "親吻對方的手腕。", level: 2 },
    { id: "cp_d_44", text: "幫對方拉拉鍊（或扣釦子）。", level: 2 },
    { id: "cp_d_45", text: "靠在對方肩膀上 1 分鐘。", level: 2 },
    { id: "cp_d_46", text: "親吻對方的鎖骨。", level: 3 },
    { id: "cp_d_47", text: "幫對方擦嘴巴。", level: 2 },
    { id: "cp_d_48", text: "摸摸對方的頭。", level: 1 },
    { id: "cp_d_49", text: "親吻對方的臉頰。", level: 1 },
    { id: "cp_d_50", text: "大聲說「你是我的」！", level: 2 },
  ],
};
